config/routes.rb
require 'sidekiq/web'
require 'api'

Analysislog::Application.routes.draw do
  resources :fiverrors


  resources :receivers
  resources :devices

  resources :events,:only=>[:index,:destroy]


  resources :messages,:only=>[:index,:create]
  match '/notes' => 'messages#note', :as => "notes", :via => :post
  match '/status' => 'messages#status', :as => "status", :via => :post

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users
  resources :users

  constraint = lambda { |request| request.env['warden'].authenticate!({ scope: :user }) }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Proton::API => '/'
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receivers }
    end
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receiver }
    end
  end

  # GET /receivers/new
  # GET /receivers/new.json
  def new
    @receiver = Receiver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receiver }
    end
  end

  # GET /receivers/1/edit
  def edit
    @receiver = Receiver.find(params[:id])
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = Receiver.new(params[:receiver])

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render json: @receiver, status: :created, location: @receiver }
      else
        format.html { render action: "new" }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receivers/1
  # PUT /receivers/1.json
  def update
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      if @receiver.update_attributes(params[:receiver])
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver = Receiver.find(params[:id])
    @receiver.destroy

    respond_to do |format|
      format.html { redirect_to receivers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/receivers/_form.html.erb
<%= form_for(@receiver) do |f| %>
  <% if @receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% @receiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receivers/edit.html.erb
<h1>Editing receiver</h1>

<%= render 'form' %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

app/views/receivers/index.html.erb
<h1>Listing receivers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receivers.each do |receiver| %>
  <tr>
    <td><%= receiver.name %></td>
    <td><%= link_to 'Show', receiver %></td>
    <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
    <td><%= link_to 'Destroy', receiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receiver', new_receiver_path %>

app/views/receivers/new.html.erb
<h1>New receiver</h1>

<%= render 'form' %>

<%= link_to 'Back', receivers_path %>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @receiver.name %>
</p>


<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>