config/routes.rb
require 'sidekiq/web'
require 'api'

Analysislog::Application.routes.draw do
  resources :fiverrors


  resources :receivers
  resources :devices

  resources :events,:only=>[:index,:destroy]


  resources :messages,:only=>[:index,:create]
  match '/notes' => 'messages#note', :as => "notes", :via => :post
  match '/status' => 'messages#status', :as => "status", :via => :post

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users
  resources :users

  constraint = lambda { |request| request.env['warden'].authenticate!({ scope: :user }) }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Proton::API => '/'
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :group_id, :hostname, :description, :rtx

  belongs_to :group, :class_name=>"DeviceGroup", :foreign_key=>"group_id"
  has_many :alerts

  def rrd_fetch()
    filename = "#{ENV['rrd_file_path']}#{self.hostname}.rrd"
    if File.exists?(filename)
      fetch_data=`#{ENV['rrd_path']} fetch #{filename} AVERAGE -s now-10minute`
      return fetch_data.split("\n")[2].split()
    end

    return []
  end

  def self.get_counts(stime,etime)
    if stime.nil? and etime.nil?
      stime = Date.today.yesterday.to_s
      etime = Date.today.to_s
    end
    counts = Array.new
    Device.all.each do |d|
      a = Hash.new
      a["devname"] = d.hostname
      a["description"] = d.description
      a["count"]   = d.alerts.where(["created_at>? and created_at<?",Time.parse(stime),Time.parse(etime)]).count
      counts << a
    end
    return counts.sort_by{|a| a["count"]}.reverse
  end

  def self.sync
    uri = URI.parse('http://rcmsapi.chinacache.com:36000/devicemrtgs')
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    devices = JSON.parse(response.body)

    devices.each do |dev|
      device = Device.where(["binary hostname=?", dev['devName']]).first
      if device
        device.update_attributes(description:dev["description"])
      end
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to devices_path}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @device = Device.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device}
    end
  end

  def create
    @device = Device.new(params[:device])
    respond_to do |format|
      if @device.save
        format.html { redirect_to devices_path, notice: 'Fiverror was successfully created.' }
        format.json { render json: @device, status: :created, location: @fiverror }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this fiverror from being saved:</h2>

      <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :hostname%>
    <%= f.text_field :hostname%>
  </div>
  <%= f.submit%>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing fiverror</h1>

<%= render 'form' %>

<%= link_to 'Show', @device%> |
<%= link_to 'Back', fiverrors_path %>

app/views/devices/index.html.erb
<table class="table">
  <thead>
    <th>
      Name
    </th>
    <th>
      RTX
    </th>
  </thead>
  <tbody>
    <% @devices.each do |device|%>
      <%= form_for(device) do |f| %>
        <tr>
          <td>
            <%= device.hostname%>
          </td>
          <td>
            On
            <%= f.radio_button :rtx, "ON"%>
            OFF
            <%= f.radio_button :rtx, "OFF"%>

            <%= f.submit :class=>"btn"%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to "New", new_device_path, class: :btn %>

app/views/devices/new.html.erb
<%= render "form" %>