config/routes.rb
require 'sidekiq/web'
require 'api'

Analysislog::Application.routes.draw do
  resources :fiverrors


  resources :receivers
  resources :devices

  resources :events,:only=>[:index,:destroy]


  resources :messages,:only=>[:index,:create]
  match '/notes' => 'messages#note', :as => "notes", :via => :post
  match '/status' => 'messages#status', :as => "status", :via => :post

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users
  resources :users

  constraint = lambda { |request| request.env['warden'].authenticate!({ scope: :user }) }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Proton::API => '/'
end

app/models/fiverror.rb
class Fiverror < ActiveRecord::Base
  attr_accessible :count, :ip, :hostname, :area
end

app/controllers/fiverrors_controller.rb
class FiverrorsController < ApplicationController
  # GET /fiverrors
  # GET /fiverrors.json
  def index
    @fiverrors = Fiverror.order("count desc").order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fiverrors }
    end
  end

  # GET /fiverrors/1
  # GET /fiverrors/1.json
  def show
    @fiverror = Fiverror.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fiverror }
    end
  end

  # GET /fiverrors/new
  # GET /fiverrors/new.json
  def new
    @fiverror = Fiverror.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fiverror }
    end
  end

  # GET /fiverrors/1/edit
  def edit
    @fiverror = Fiverror.find(params[:id])
  end

  # POST /fiverrors
  # POST /fiverrors.json
  def create
    @fiverror = Fiverror.new(params[:fiverror])
    @fiverror.area = Message.getisp(@fiverror.ip)
    respond_to do |format|
      if @fiverror.save
        format.html { redirect_to @fiverror, notice: 'Fiverror was successfully created.' }
        format.json { render json: @fiverror, status: :created, location: @fiverror }
      else
        format.html { render action: "new" }
        format.json { render json: @fiverror.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fiverrors/1
  # PUT /fiverrors/1.json
  def update
    @fiverror = Fiverror.find(params[:id])

    respond_to do |format|
      if @fiverror.update_attributes(params[:fiverror])
        format.html { redirect_to @fiverror, notice: 'Fiverror was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fiverror.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiverrors/1
  # DELETE /fiverrors/1.json
  def destroy
    @fiverror = Fiverror.find(params[:id])
    @fiverror.destroy

    respond_to do |format|
      format.html { redirect_to fiverrors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fiverrors_helper.rb
module FiverrorsHelper
end

app/views/fiverrors/_form.html.erb
<%= form_for(@fiverror) do |f| %>
  <% if @fiverror.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiverror.errors.count, "error") %> prohibited this fiverror from being saved:</h2>

      <ul>
      <% @fiverror.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiverrors/edit.html.erb
<h1>Editing fiverror</h1>

<%= render 'form' %>

<%= link_to 'Show', @fiverror %> |
<%= link_to 'Back', fiverrors_path %>

app/views/fiverrors/index.html.erb
<h1>Listing fiverrors</h1>

<table class="table">
  <tr>
    <th>area</th>
    <th>Ip</th>
    <th>Hostname</th>
    <th>Count</th>
    <th>CreateAt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fiverrors.each do |fiverror| %>
  <tr>
    <td><%= fiverror.area %></td>
    <td><%= fiverror.ip %></td>
    <td><%= fiverror.hostname %></td>
    <td><%= fiverror.count %></td>
    <td><%= fiverror.created_at %></td>
    <td><%= link_to 'Show', fiverror %></td>
    <td><%= link_to 'Edit', edit_fiverror_path(fiverror) %></td>
    <td><%= link_to 'Destroy', fiverror, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fiverror', new_fiverror_path %>

app/views/fiverrors/new.html.erb
<h1>New fiverror</h1>

<%= render 'form' %>

<%= link_to 'Back', fiverrors_path %>

app/views/fiverrors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ip:</b>
  <%= @fiverror.ip %>
</p>

<p>
  <b>Count:</b>
  <%= @fiverror.count %>
</p>


<%= link_to 'Edit', edit_fiverror_path(@fiverror) %> |
<%= link_to 'Back', fiverrors_path %>